services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: dev.Dockerfile
  #   ports:
  #     - ${APP_LISTEN_PORT}:${APP_LISTEN_PORT}
  #   depends_on:
  #     - postgres
  #   volumes:
  #     - ./:/app
  #   networks:
  #     - template-network

  postgres:
    image: "postgres:16.2"
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_ROOT_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_ROOT_HOST: "%"
      POSTGRES_DATABASE: "${POSTGRES_DB_NAME}"
      POSTGRES_USER: "${POSTGRES_USERNAME}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - "template-postgres:/var/lib/postgresql/data"
    networks:
      - template-network

networks:
  template-network:
    driver: bridge

volumes:
  template-postgres:
    driver: local
